// Mascot dataset. `logo` URLs use ESPN's CDN (publicly cached).
// `emoji` is a fallback if a logo URL fails.
// For college, `city` stores the school name; `league` stores the conference.
const ESPN = (sport, abbr) =>
  `https://a.espncdn.com/i/teamlogos/${sport}/500/${abbr}.png`;
const NCAA = (id) => `https://a.espncdn.com/i/teamlogos/ncaa/500/${id}.png`;
const SOCCER = (id) => `https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png`;
// Some MLS teams 404 on the soccer/{id} path but work via the mls/{abbr} path.
const MLS = (abbr) => `https://a.espncdn.com/i/teamlogos/mls/500/${abbr}.png`;

const IMG = (slug) => `images/mascots/${slug}.png`;

window.MASCOTS = [
  // ---------- PRO: MLB ----------
  {
    name: "Phillie Phanatic",
    team: "Phillies",
    city: "Philadelphia",
    league: "MLB",
    animal: "creature",
    emoji: "🟢",
    level: "pro",
    logo: ESPN("mlb", "phi"),
    image: IMG("phillie-phanatic"),
  },
  {
    name: "Mr. Met",
    team: "Mets",
    city: "New York",
    league: "MLB",
    animal: "human",
    emoji: "⚾",
    level: "pro",
    logo: ESPN("mlb", "nym"),
    image: IMG("mr-met"),
  },
  {
    name: "Mrs. Met",
    team: "Mets",
    city: "New York",
    league: "MLB",
    animal: "human",
    emoji: "⚾",
    level: "pro",
    logo: ESPN("mlb", "nym"),
    image: IMG("mrs-met"),
  },
  {
    name: "Billy the Marlin",
    team: "Marlins",
    city: "Miami",
    league: "MLB",
    animal: "fish",
    emoji: "🐟",
    level: "pro",
    logo: ESPN("mlb", "mia"),
    image: IMG("billy-the-marlin"),
  },
  {
    name: "Slider",
    team: "Guardians",
    city: "Cleveland",
    league: "MLB",
    animal: "creature",
    emoji: "🟣",
    level: "pro",
    logo: ESPN("mlb", "cle"),
    image: IMG("slider"),
  },
  {
    name: "Wally",
    team: "Red Sox",
    city: "Boston",
    league: "MLB",
    animal: "creature",
    emoji: "🟩",
    level: "pro",
    logo: ESPN("mlb", "bos"),
    image: IMG("wally"),
  },
  {
    name: "Bernie Brewer",
    team: "Brewers",
    city: "Milwaukee",
    league: "MLB",
    animal: "human",
    emoji: "🍺",
    level: "pro",
    logo: ESPN("mlb", "mil"),
    image: IMG("bernie-brewer"),
  },
  {
    name: "Orbit",
    team: "Astros",
    city: "Houston",
    league: "MLB",
    animal: "alien",
    emoji: "👽",
    level: "pro",
    logo: ESPN("mlb", "hou"),
    image: IMG("orbit"),
  },
  {
    name: "Paws",
    team: "Tigers",
    city: "Detroit",
    league: "MLB",
    animal: "tiger",
    emoji: "🐯",
    level: "pro",
    logo: ESPN("mlb", "det"),
    image: IMG("paws"),
  },
  {
    name: "Fredbird",
    team: "Cardinals",
    city: "St. Louis",
    league: "MLB",
    animal: "bird",
    emoji: "🐦",
    level: "pro",
    logo: ESPN("mlb", "stl"),
    image: IMG("fredbird"),
  },
  {
    name: "Lou Seal",
    team: "Giants",
    city: "San Francisco",
    league: "MLB",
    animal: "seal",
    emoji: "🦭",
    level: "pro",
    logo: ESPN("mlb", "sf"),
    image: IMG("lou-seal"),
  },
  {
    name: "Dinger",
    team: "Rockies",
    city: "Denver",
    league: "MLB",
    animal: "dinosaur",
    emoji: "🦖",
    level: "pro",
    logo: ESPN("mlb", "col"),
    image: IMG("dinger"),
  },
  {
    name: "Pirate Parrot",
    team: "Pirates",
    city: "Pittsburgh",
    league: "MLB",
    animal: "parrot",
    emoji: "🦜",
    level: "pro",
    logo: ESPN("mlb", "pit"),
    image: IMG("pirate-parrot"),
  },
  {
    name: "Raymond",
    team: "Rays",
    city: "St. Petersburg",
    league: "MLB",
    animal: "creature",
    emoji: "🟦",
    level: "pro",
    logo: ESPN("mlb", "tb"),
    image: IMG("raymond"),
  },
  {
    name: "Stomper",
    team: "Athletics",
    city: "Oakland",
    league: "MLB",
    animal: "elephant",
    emoji: "🐘",
    level: "pro",
    logo: ESPN("mlb", "oak"),
    image: IMG("stomper"),
  },
  {
    name: "Mariner Moose",
    team: "Mariners",
    city: "Seattle",
    league: "MLB",
    animal: "moose",
    emoji: "🫎",
    level: "pro",
    logo: ESPN("mlb", "sea"),
    image: IMG("mariner-moose"),
  },
  {
    name: "Ace",
    team: "Blue Jays",
    city: "Toronto",
    league: "MLB",
    animal: "bird",
    emoji: "🐦",
    level: "pro",
    logo: ESPN("mlb", "tor"),
    image: IMG("ace"),
  },
  {
    name: "Southpaw",
    team: "White Sox",
    city: "Chicago",
    league: "MLB",
    animal: "creature",
    emoji: "🟨",
    level: "pro",
    logo: ESPN("mlb", "cws"),
    image: IMG("southpaw"),
  },
  {
    name: "Screech",
    team: "Nationals",
    city: "Washington",
    league: "MLB",
    animal: "eagle",
    emoji: "🦅",
    level: "pro",
    logo: ESPN("mlb", "wsh"),
    image: IMG("screech"),
  },
  {
    name: "Clark",
    team: "Cubs",
    city: "Chicago",
    league: "MLB",
    animal: "bear",
    emoji: "🐻",
    level: "pro",
    logo: ESPN("mlb", "chc"),
    image: IMG("clark"),
  },
  {
    name: "T.C. Bear",
    team: "Twins",
    city: "Minneapolis",
    league: "MLB",
    animal: "bear",
    emoji: "🐻",
    level: "pro",
    logo: ESPN("mlb", "min"),
    image: IMG("tc-bear"),
  },
  {
    name: "Rangers Captain",
    team: "Rangers",
    city: "Arlington",
    league: "MLB",
    animal: "horse",
    emoji: "🐴",
    level: "pro",
    logo: ESPN("mlb", "tex"),
    image: IMG("rally-horse"),
  },
  {
    name: "D. Baxter",
    team: "Diamondbacks",
    city: "Phoenix",
    league: "MLB",
    animal: "bobcat",
    emoji: "🐱",
    level: "pro",
    logo: ESPN("mlb", "ari"),
    image: IMG("baxter"),
  },
  {
    name: "Swinging Friar",
    team: "Padres",
    city: "San Diego",
    league: "MLB",
    animal: "human",
    emoji: "🧔",
    level: "pro",
    logo: ESPN("mlb", "sd"),
    image: IMG("swinging-friar"),
  },

  // ---------- PRO: NBA ----------
  {
    name: "Burnie",
    team: "Heat",
    city: "Miami",
    league: "NBA",
    animal: "fire",
    emoji: "🔥",
    level: "pro",
    logo: ESPN("nba", "mia"),
    image: IMG("burnie"),
  },
  {
    name: "Stuff the Magic Dragon",
    team: "Magic",
    city: "Orlando",
    league: "NBA",
    animal: "dragon",
    emoji: "🐉",
    level: "pro",
    logo: ESPN("nba", "orl"),
    image: IMG("stuff-magic"),
  },
  {
    name: "Harry the Hawk",
    team: "Hawks",
    city: "Atlanta",
    league: "NBA",
    animal: "bird",
    emoji: "🦅",
    level: "pro",
    logo: ESPN("nba", "atl"),
    image: IMG("harry-the-hawk"),
  },
  {
    name: "Benny the Bull",
    team: "Bulls",
    city: "Chicago",
    league: "NBA",
    animal: "bull",
    emoji: "🐂",
    level: "pro",
    logo: ESPN("nba", "chi"),
    image: IMG("benny-the-bull"),
  },
  {
    name: "The Coyote",
    team: "Spurs",
    city: "San Antonio",
    league: "NBA",
    animal: "coyote",
    emoji: "🐺",
    level: "pro",
    logo: ESPN("nba", "sa"),
    image: IMG("the-coyote"),
  },
  {
    name: "Rumble the Bison",
    team: "Thunder",
    city: "Oklahoma City",
    league: "NBA",
    animal: "bison",
    emoji: "🐃",
    level: "pro",
    logo: ESPN("nba", "okc"),
    image: IMG("rumble"),
  },
  {
    name: "Rocky",
    team: "Nuggets",
    city: "Denver",
    league: "NBA",
    animal: "mountain-lion",
    emoji: "🦁",
    level: "pro",
    logo: ESPN("nba", "den"),
    image: IMG("rocky"),
  },
  {
    name: "Clutch",
    team: "Rockets",
    city: "Houston",
    league: "NBA",
    animal: "bear",
    emoji: "🐻",
    level: "pro",
    logo: ESPN("nba", "hou"),
    image: IMG("clutch"),
  },
  {
    name: "Chuck the Condor",
    team: "Clippers",
    city: "Los Angeles",
    league: "NBA",
    animal: "condor",
    emoji: "🦅",
    level: "pro",
    logo: ESPN("nba", "lac"),
    image: IMG("chuck-condor"),
  },
  {
    name: "Hugo",
    team: "Hornets",
    city: "Charlotte",
    league: "NBA",
    animal: "hornet",
    emoji: "🐝",
    level: "pro",
    logo: ESPN("nba", "cha"),
    image: IMG("hugo"),
  },
  {
    name: "The Gorilla",
    team: "Suns",
    city: "Phoenix",
    league: "NBA",
    animal: "gorilla",
    emoji: "🦍",
    level: "pro",
    logo: ESPN("nba", "phx"),
    image: IMG("gorilla"),
  },
  {
    name: "Bango",
    team: "Bucks",
    city: "Milwaukee",
    league: "NBA",
    animal: "deer",
    emoji: "🦌",
    level: "pro",
    logo: ESPN("nba", "mil"),
    image: IMG("bango"),
  },
  {
    name: "Slamson the Lion",
    team: "Kings",
    city: "Sacramento",
    league: "NBA",
    animal: "lion",
    emoji: "🦁",
    level: "pro",
    logo: ESPN("nba", "sac"),
    image: IMG("slamson"),
  },
  {
    name: "Moondog",
    team: "Cavaliers",
    city: "Cleveland",
    league: "NBA",
    animal: "dog",
    emoji: "🐶",
    level: "pro",
    logo: ESPN("nba", "cle"),
    image: IMG("moondog"),
  },
  {
    name: "Boomer",
    team: "Pacers",
    city: "Indianapolis",
    league: "NBA",
    animal: "panther",
    emoji: "🐱",
    level: "pro",
    logo: ESPN("nba", "ind"),
    image: IMG("boomer"),
  },
  {
    name: "Champ",
    team: "Mavericks",
    city: "Dallas",
    league: "NBA",
    animal: "horse",
    emoji: "🐴",
    level: "pro",
    logo: ESPN("nba", "dal"),
    image: IMG("champ"),
  },
  {
    name: "Grizz",
    team: "Grizzlies",
    city: "Memphis",
    league: "NBA",
    animal: "bear",
    emoji: "🐻",
    level: "pro",
    logo: ESPN("nba", "mem"),
    image: IMG("grizz"),
  },
  {
    name: "The Raptor",
    team: "Raptors",
    city: "Toronto",
    league: "NBA",
    animal: "raptor",
    emoji: "🦖",
    level: "pro",
    logo: ESPN("nba", "tor"),
    image: IMG("raptor"),
  },
  {
    name: "Blaze the Trail Cat",
    team: "Trail Blazers",
    city: "Portland",
    league: "NBA",
    animal: "cat",
    emoji: "🐱",
    level: "pro",
    logo: ESPN("nba", "por"),
    image: IMG("blaze"),
  },
  {
    name: "Franklin the Dog",
    team: "76ers",
    city: "Philadelphia",
    league: "NBA",
    animal: "dog",
    emoji: "🐶",
    level: "pro",
    logo: ESPN("nba", "phi"),
    image: IMG("franklin"),
  },
  {
    name: "Jazz Bear",
    team: "Jazz",
    city: "Salt Lake City",
    league: "NBA",
    animal: "bear",
    emoji: "🐻",
    level: "pro",
    logo: ESPN("nba", "utah"),
    image: IMG("jazz-bear"),
  },
  {
    name: "G-Wiz",
    team: "Wizards",
    city: "Washington",
    league: "NBA",
    animal: "creature",
    emoji: "🟣",
    level: "pro",
    logo: ESPN("nba", "wsh"),
    image: IMG("g-wiz"),
  },

  // ---------- PRO: NFL ----------
  {
    name: "Swoop",
    team: "Eagles",
    city: "Philadelphia",
    league: "NFL",
    animal: "bird",
    emoji: "🦅",
    level: "pro",
    logo: ESPN("nfl", "phi"),
    image: IMG("swoop"),
  },
  {
    name: "Pat Patriot",
    team: "Patriots",
    city: "Foxborough",
    league: "NFL",
    animal: "human",
    emoji: "🎩",
    level: "pro",
    logo: ESPN("nfl", "ne"),
    image: IMG("pat-patriot"),
  },
  {
    name: "Billy Buffalo",
    team: "Bills",
    city: "Buffalo",
    league: "NFL",
    animal: "buffalo",
    emoji: "🐃",
    level: "pro",
    logo: ESPN("nfl", "buf"),
    image: IMG("billy-buffalo"),
  },
  {
    name: "T.D.",
    team: "Dolphins",
    city: "Miami",
    league: "NFL",
    animal: "dolphin",
    emoji: "🐬",
    level: "pro",
    logo: ESPN("nfl", "mia"),
    image: IMG("td"),
  },
  {
    name: "Poe",
    team: "Ravens",
    city: "Baltimore",
    league: "NFL",
    animal: "raven",
    emoji: "🐦",
    level: "pro",
    logo: ESPN("nfl", "bal"),
    image: IMG("poe"),
  },
  {
    name: "Who Dey",
    team: "Bengals",
    city: "Cincinnati",
    league: "NFL",
    animal: "tiger",
    emoji: "🐯",
    level: "pro",
    logo: ESPN("nfl", "cin"),
    image: IMG("who-dey"),
  },
  {
    name: "Chomps",
    team: "Browns",
    city: "Cleveland",
    league: "NFL",
    animal: "dog",
    emoji: "🐶",
    level: "pro",
    logo: ESPN("nfl", "cle"),
    image: IMG("chomps"),
  },
  {
    name: "Steel Curtain",
    team: "Steelers",
    city: "Pittsburgh",
    league: "NFL",
    animal: "creature",
    emoji: "🟡",
    level: "pro",
    logo: ESPN("nfl", "pit"),
    image: IMG("steel-curtain"),
  },
  {
    name: "Toro",
    team: "Texans",
    city: "Houston",
    league: "NFL",
    animal: "bull",
    emoji: "🐂",
    level: "pro",
    logo: ESPN("nfl", "hou"),
    image: IMG("toro"),
  },
  {
    name: "Blue",
    team: "Colts",
    city: "Indianapolis",
    league: "NFL",
    animal: "horse",
    emoji: "🐎",
    level: "pro",
    logo: ESPN("nfl", "ind"),
    image: IMG("blue"),
  },
  {
    name: "Jaxson de Ville",
    team: "Jaguars",
    city: "Jacksonville",
    league: "NFL",
    animal: "jaguar",
    emoji: "🐆",
    level: "pro",
    logo: ESPN("nfl", "jax"),
    image: IMG("jaxson-de-ville"),
  },
  {
    name: "T-Rac",
    team: "Titans",
    city: "Nashville",
    league: "NFL",
    animal: "raccoon",
    emoji: "🦝",
    level: "pro",
    logo: ESPN("nfl", "ten"),
    image: IMG("t-rac"),
  },
  {
    name: "Miles",
    team: "Broncos",
    city: "Denver",
    league: "NFL",
    animal: "horse",
    emoji: "🐴",
    level: "pro",
    logo: ESPN("nfl", "den"),
    image: IMG("miles"),
  },
  {
    name: "KC Wolf",
    team: "Chiefs",
    city: "Kansas City",
    league: "NFL",
    animal: "wolf",
    emoji: "🐺",
    level: "pro",
    logo: ESPN("nfl", "kc"),
    image: IMG("kc-wolf"),
  },
  {
    name: "Raider Rush",
    team: "Raiders",
    city: "Las Vegas",
    league: "NFL",
    animal: "human",
    emoji: "🏴‍☠️",
    level: "pro",
    logo: ESPN("nfl", "lv"),
    image: IMG("raider-rush"),
  },
  {
    name: "Rowdy",
    team: "Cowboys",
    city: "Arlington",
    league: "NFL",
    animal: "human",
    emoji: "🤠",
    level: "pro",
    logo: ESPN("nfl", "dal"),
    image: IMG("rowdy"),
  },
  {
    name: "Major Tuddy",
    team: "Commanders",
    city: "Washington",
    league: "NFL",
    animal: "pig",
    emoji: "🐷",
    level: "pro",
    logo: ESPN("nfl", "wsh"),
    image: IMG("major-tuddy"),
  },
  {
    name: "Staley da Bear",
    team: "Bears",
    city: "Chicago",
    league: "NFL",
    animal: "bear",
    emoji: "🐻",
    level: "pro",
    logo: ESPN("nfl", "chi"),
    image: IMG("staley-da-bear"),
  },
  {
    name: "Roary",
    team: "Lions",
    city: "Detroit",
    league: "NFL",
    animal: "lion",
    emoji: "🦁",
    level: "pro",
    logo: ESPN("nfl", "det"),
    image: IMG("roary"),
  },
  {
    name: "Viktor",
    team: "Vikings",
    city: "Minneapolis",
    league: "NFL",
    animal: "human",
    emoji: "🪓",
    level: "pro",
    logo: ESPN("nfl", "min"),
    image: IMG("viktor"),
  },
  {
    name: "Freddie Falcon",
    team: "Falcons",
    city: "Atlanta",
    league: "NFL",
    animal: "falcon",
    emoji: "🦅",
    level: "pro",
    logo: ESPN("nfl", "atl"),
    image: IMG("freddie-falcon"),
  },
  {
    name: "Sir Purr",
    team: "Panthers",
    city: "Charlotte",
    league: "NFL",
    animal: "panther",
    emoji: "🐱",
    level: "pro",
    logo: ESPN("nfl", "car"),
    image: IMG("sir-purr"),
  },
  {
    name: "Gumbo",
    team: "Saints",
    city: "New Orleans",
    league: "NFL",
    animal: "dog",
    emoji: "🐶",
    level: "pro",
    logo: ESPN("nfl", "no"),
    image: IMG("gumbo"),
  },
  {
    name: "Captain Fear",
    team: "Buccaneers",
    city: "Tampa",
    league: "NFL",
    animal: "human",
    emoji: "🏴‍☠️",
    level: "pro",
    logo: ESPN("nfl", "tb"),
    image: IMG("captain-fear"),
  },
  {
    name: "Big Red",
    team: "Cardinals",
    city: "Glendale",
    league: "NFL",
    animal: "bird",
    emoji: "🐦",
    level: "pro",
    logo: ESPN("nfl", "ari"),
    image: IMG("big-red"),
  },
  {
    name: "Rampage",
    team: "Rams",
    city: "Los Angeles",
    league: "NFL",
    animal: "ram",
    emoji: "🐏",
    level: "pro",
    logo: ESPN("nfl", "lar"),
    image: IMG("rampage"),
  },
  {
    name: "Blitz",
    team: "Seahawks",
    city: "Seattle",
    league: "NFL",
    animal: "bird",
    emoji: "🦅",
    level: "pro",
    logo: ESPN("nfl", "sea"),
    image: IMG("blitz"),
  },
  {
    name: "Sourdough Sam",
    team: "49ers",
    city: "San Francisco",
    league: "NFL",
    animal: "human",
    emoji: "⛏️",
    level: "pro",
    logo: ESPN("nfl", "sf"),
    image: IMG("sourdough-sam"),
  },

  // ---------- PRO: NHL ----------
  {
    name: "Gritty",
    team: "Flyers",
    city: "Philadelphia",
    league: "NHL",
    animal: "creature",
    emoji: "🟠",
    level: "pro",
    logo: ESPN("nhl", "phi"),
    image: IMG("gritty"),
  },
  {
    name: "Stanley C. Panther",
    team: "Panthers",
    city: "Sunrise",
    league: "NHL",
    animal: "panther",
    emoji: "🐆",
    level: "pro",
    logo: ESPN("nhl", "fla"),
    image: IMG("stanley-c-panther"),
  },
  {
    name: "Youppi!",
    team: "Canadiens",
    city: "Montreal",
    league: "NHL",
    animal: "creature",
    emoji: "🟧",
    level: "pro",
    logo: ESPN("nhl", "mtl"),
    image: IMG("youppi"),
  },
  {
    name: "Iceburgh",
    team: "Penguins",
    city: "Pittsburgh",
    league: "NHL",
    animal: "penguin",
    emoji: "🐧",
    level: "pro",
    logo: ESPN("nhl", "pit"),
    image: IMG("iceburgh"),
  },
  {
    name: "Bailey",
    team: "Kings",
    city: "Los Angeles",
    league: "NHL",
    animal: "lion",
    emoji: "🦁",
    level: "pro",
    logo: ESPN("nhl", "la"),
    image: IMG("bailey"),
  },
  {
    name: "N.J. Devil",
    team: "Devils",
    city: "Newark",
    league: "NHL",
    animal: "devil",
    emoji: "😈",
    level: "pro",
    logo: ESPN("nhl", "nj"),
    image: IMG("nj-devil"),
  },
  {
    name: "Carlton the Bear",
    team: "Maple Leafs",
    city: "Toronto",
    league: "NHL",
    animal: "bear",
    emoji: "🐻",
    level: "pro",
    logo: ESPN("nhl", "tor"),
    image: IMG("carlton"),
  },
  {
    name: "Sparky the Dragon",
    team: "Islanders",
    city: "New York",
    league: "NHL",
    animal: "dragon",
    emoji: "🐉",
    level: "pro",
    logo: ESPN("nhl", "nyi"),
    image: IMG("sparky-islanders"),
  },
  {
    name: "S.J. Sharkie",
    team: "Sharks",
    city: "San Jose",
    league: "NHL",
    animal: "shark",
    emoji: "🦈",
    level: "pro",
    logo: ESPN("nhl", "sj"),
    image: IMG("sj-sharkie"),
  },
  {
    name: "Gnash",
    team: "Predators",
    city: "Nashville",
    league: "NHL",
    animal: "saber-cat",
    emoji: "🐯",
    level: "pro",
    logo: ESPN("nhl", "nsh"),
    image: IMG("gnash"),
  },
  {
    name: "Nordy",
    team: "Wild",
    city: "Saint Paul",
    league: "NHL",
    animal: "creature",
    emoji: "🐾",
    level: "pro",
    logo: ESPN("nhl", "min"),
    image: IMG("nordy"),
  },
  {
    name: "Tommy Hawk",
    team: "Blackhawks",
    city: "Chicago",
    league: "NHL",
    animal: "bird",
    emoji: "🦅",
    level: "pro",
    logo: ESPN("nhl", "chi"),
    image: IMG("tommy-hawk"),
  },
  {
    name: "Howler",
    team: "Coyotes",
    city: "Glendale",
    league: "NHL",
    animal: "coyote",
    emoji: "🐺",
    level: "pro",
    logo: ESPN("nhl", "ari"),
    image: IMG("howler"),
  },
  {
    name: "Louie",
    team: "Blues",
    city: "St. Louis",
    league: "NHL",
    animal: "bear",
    emoji: "🐻",
    level: "pro",
    logo: ESPN("nhl", "stl"),
    image: IMG("louie"),
  },
  {
    name: "Bernie",
    team: "Avalanche",
    city: "Denver",
    league: "NHL",
    animal: "dog",
    emoji: "🐶",
    level: "pro",
    logo: ESPN("nhl", "col"),
    image: IMG("bernie"),
  },
  {
    name: "Sabretooth",
    team: "Sabres",
    city: "Buffalo",
    league: "NHL",
    animal: "saber-cat",
    emoji: "🐯",
    level: "pro",
    logo: ESPN("nhl", "buf"),
    image: IMG("sabretooth"),
  },
  {
    name: "Buoy",
    team: "Kraken",
    city: "Seattle",
    league: "NHL",
    animal: "creature",
    emoji: "🟦",
    level: "pro",
    logo: ESPN("nhl", "sea"),
    image: IMG("buoy"),
  },

  // ---------- PRO: MLS ----------
  {
    name: "Talon",
    team: "United",
    city: "Atlanta",
    league: "MLS",
    animal: "bird",
    emoji: "🦅",
    level: "pro",
    logo: SOCCER(18418),
    image: IMG("talon"),
  },
  {
    name: "Kingston",
    team: "Galaxy",
    city: "Los Angeles",
    league: "MLS",
    animal: "lion",
    emoji: "🦁",
    level: "pro",
    logo: SOCCER(187),
    image: IMG("kingston"),
  },
  {
    name: "Tac-Tik",
    team: "CF Montréal",
    city: "Montreal",
    league: "MLS",
    animal: "raccoon",
    emoji: "🦝",
    level: "pro",
    logo: SOCCER(9720),
    image: IMG("tac-tik"),
  },
  {
    name: "Diesel",
    team: "Dynamo",
    city: "Houston",
    league: "MLS",
    animal: "dog",
    emoji: "🐶",
    level: "pro",
    logo: SOCCER(6077),
    image: IMG("diesel-dynamo"),
  },
  {
    name: "Rhinoman",
    team: "Red Bulls",
    city: "Harrison",
    league: "MLS",
    animal: "rhino",
    emoji: "🦏",
    level: "pro",
    logo: SOCCER(190),
    image: IMG("rhinoman"),
  },
  {
    name: "Clawhauser",
    team: "Crew",
    city: "Columbus",
    league: "MLS",
    animal: "jaguar",
    emoji: "🐆",
    level: "pro",
    logo: SOCCER(192),
    image: IMG("clawhauser"),
    noLogo: true,
  },
  {
    name: "Swoop",
    team: "Union",
    city: "Philadelphia",
    league: "MLS",
    animal: "eagle",
    emoji: "🦅",
    level: "pro",
    logo: SOCCER(10739),
    image: IMG("swoop-mls"),
  },
  {
    name: "Shelly",
    team: "Revolution",
    city: "Foxborough",
    league: "MLS",
    animal: "turtle",
    emoji: "🐢",
    level: "pro",
    logo: SOCCER(189),
    image: IMG("shelly"),
  },
  {
    name: "Redbird",
    team: "City SC",
    city: "St. Louis",
    league: "MLS",
    animal: "bird",
    emoji: "🐦",
    level: "pro",
    logo: SOCCER(21812),
    image: IMG("redbird"),
  },
  {
    name: "Panther",
    team: "Inter Miami",
    city: "Miami",
    league: "MLS",
    animal: "panther",
    emoji: "🐆",
    level: "pro",
    logo: SOCCER(20232),
    image: IMG("panther"),
  },
  {
    name: "King",
    team: "Orlando City",
    city: "Orlando",
    league: "MLS",
    animal: "lion",
    emoji: "🦁",
    level: "pro",
    logo: SOCCER(12011),
    image: IMG("king"),
  },
  {
    name: "Take Flight",
    team: "Earthquakes",
    city: "San Jose",
    league: "MLS",
    animal: "bird",
    emoji: "🦅",
    level: "pro",
    logo: SOCCER(191),
    image: IMG("take-flight"),
  },
  {
    name: "Wolfie",
    team: "United FC",
    city: "Saint Paul",
    league: "MLS",
    animal: "wolf",
    emoji: "🐺",
    level: "pro",
    logo: SOCCER(17362),
    image: IMG("wolfie"),
  },
  {
    name: "Marco",
    team: "Rapids",
    city: "Commerce City",
    league: "MLS",
    animal: "goat",
    emoji: "🐐",
    level: "pro",
    logo: SOCCER(182),
    image: IMG("marco-rapids"),
  },
  {
    name: "Timber Joey",
    team: "Timbers",
    city: "Portland",
    league: "MLS",
    animal: "human",
    emoji: "🪓",
    level: "pro",
    logo: SOCCER(9723),
    image: IMG("timber-joey"),
  },
  {
    name: "Verde the Armadillo",
    team: "Austin FC",
    city: "Austin",
    league: "MLS",
    animal: "armadillo",
    emoji: "🦔",
    level: "pro",
    logo: SOCCER(20906),
    image: IMG("verde-armadillo"),
  },
  {
    name: "Sparky",
    team: "Fire FC",
    city: "Chicago",
    league: "MLS",
    animal: "dog",
    emoji: "🐶",
    level: "pro",
    logo: MLS("chi"),
    image: IMG("sparky-mls"),
  },
  {
    name: "Finley",
    team: "Whitecaps",
    city: "Vancouver",
    league: "MLS",
    animal: "creature",
    emoji: "🟦",
    level: "pro",
    logo: SOCCER(9727),
    image: IMG("finley"),
  },
  {
    name: "Bucky",
    team: "Real Salt Lake",
    city: "Salt Lake City",
    league: "MLS",
    animal: "ram",
    emoji: "🐏",
    level: "pro",
    logo: SOCCER(4771),
    image: IMG("bucky"),
  },
  {
    name: "Blue",
    team: "Sporting KC",
    city: "Kansas City",
    league: "MLS",
    animal: "dog",
    emoji: "🐶",
    level: "pro",
    logo: SOCCER(186),
    image: IMG("blue-skc"),
  },
  {
    name: "Soundi",
    team: "Sounders",
    city: "Seattle",
    league: "MLS",
    animal: "orca",
    emoji: "🐋",
    level: "pro",
    logo: MLS("sea"),
    image: IMG("soundi"),
  },
  {
    name: "Hoots",
    team: "D.C. United",
    city: "Washington",
    league: "MLS",
    animal: "owl",
    emoji: "🦉",
    level: "pro",
    logo: SOCCER(193),
    image: IMG("hoots"),
  },
  {
    name: "Chomps",
    team: "Nashville SC",
    city: "Nashville",
    league: "MLS",
    animal: "creature",
    emoji: "🟢",
    level: "pro",
    logo: SOCCER(18986),
    image: IMG("chomps-mls"),
  },

  // ---------- COLLEGE D1 ----------
  // Big Ten
  {
    name: "Brutus Buckeye",
    team: "Buckeyes",
    city: "Ohio State",
    league: "Big Ten",
    animal: "buckeye",
    emoji: "🌰",
    level: "college",
    logo: NCAA(194),
    image: IMG("brutus-buckeye"),
  },
  {
    name: "Sparty",
    team: "Spartans",
    city: "Michigan State",
    league: "Big Ten",
    animal: "spartan",
    emoji: "⚔️",
    level: "college",
    logo: NCAA(127),
    image: IMG("sparty"),
  },
  {
    name: "Goldy Gopher",
    team: "Golden Gophers",
    city: "Minnesota",
    league: "Big Ten",
    animal: "gopher",
    emoji: "🐹",
    level: "college",
    logo: NCAA(135),
    image: IMG("goldy-gopher"),
  },
  {
    name: "Bucky Badger",
    team: "Badgers",
    city: "Wisconsin",
    league: "Big Ten",
    animal: "badger",
    emoji: "🦡",
    level: "college",
    logo: NCAA(275),
    image: IMG("bucky-badger"),
  },
  {
    name: "Herbie Husker",
    team: "Cornhuskers",
    city: "Nebraska",
    league: "Big Ten",
    animal: "human",
    emoji: "🌽",
    level: "college",
    logo: NCAA(158),
    image: IMG("herbie-husker"),
  },
  {
    name: "The Oregon Duck",
    team: "Ducks",
    city: "Oregon",
    league: "Big Ten",
    animal: "duck",
    emoji: "🦆",
    level: "college",
    logo: NCAA(2483),
    image: IMG("oregon-duck"),
  },
  {
    name: "Joe Bruin",
    team: "Bruins",
    city: "UCLA",
    league: "Big Ten",
    animal: "bear",
    emoji: "🐻",
    level: "college",
    logo: NCAA(26),
    image: IMG("joe-bruin"),
  },
  {
    name: "Testudo",
    team: "Terrapins",
    city: "Maryland",
    league: "Big Ten",
    animal: "turtle",
    emoji: "🐢",
    level: "college",
    logo: NCAA(120),
    image: IMG("testudo"),
  },
  {
    name: "Hoosier the Bison",
    team: "Hoosiers",
    city: "Indiana",
    league: "Big Ten",
    animal: "bison",
    emoji: "🐃",
    level: "college",
    logo: NCAA(84),
    image: IMG("hoosier-the-bison"),
  },
  {
    name: "Herky the Hawk",
    team: "Hawkeyes",
    city: "Iowa",
    league: "Big Ten",
    animal: "hawk",
    emoji: "🦅",
    level: "college",
    logo: NCAA(2294),
    image: IMG("herky-the-hawk"),
  },
  {
    name: "Willie the Wildcat",
    team: "Wildcats",
    city: "Northwestern",
    league: "Big Ten",
    animal: "wildcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(77),
    image: IMG("willie-the-wildcat-nu"),
  },
  {
    name: "Nittany Lion",
    team: "Nittany Lions",
    city: "Penn State",
    league: "Big Ten",
    animal: "lion",
    emoji: "🦁",
    level: "college",
    logo: NCAA(213),
    image: IMG("nittany-lion"),
  },
  {
    name: "Purdue Pete",
    team: "Boilermakers",
    city: "Purdue",
    league: "Big Ten",
    animal: "human",
    emoji: "🔨",
    level: "college",
    logo: NCAA(2509),
    image: IMG("purdue-pete"),
  },
  {
    name: "Scarlet Knight",
    team: "Scarlet Knights",
    city: "Rutgers",
    league: "Big Ten",
    animal: "knight",
    emoji: "⚔️",
    level: "college",
    logo: NCAA(164),
    image: IMG("scarlet-knight"),
  },
  {
    name: "Tommy Trojan",
    team: "Trojans",
    city: "USC",
    league: "Big Ten",
    animal: "human",
    emoji: "🛡️",
    level: "college",
    logo: NCAA(30),
    image: IMG("tommy-trojan"),
  },
  {
    name: "Harry the Husky",
    team: "Huskies",
    city: "Washington",
    league: "Big Ten",
    animal: "husky",
    emoji: "🐶",
    level: "college",
    logo: NCAA(264),
    image: IMG("harry-the-husky"),
    state: "WA",
  },

  {
    name: "Sebastian the Ibis",
    team: "Hurricanes",
    city: "Miami",
    league: "ACC",
    animal: "ibis",
    emoji: "🦩",
    level: "college",
    logo: NCAA(2390),
    image: IMG("sebastian-ibis"),
  },
  {
    name: "Hokie Bird",
    team: "Hokies",
    city: "Virginia Tech",
    league: "ACC",
    animal: "turkey",
    emoji: "🦃",
    level: "college",
    logo: NCAA(259),
    image: IMG("hokie-bird"),
  },
  {
    name: "Otto the Orange",
    team: "Orange",
    city: "Syracuse",
    league: "ACC",
    animal: "fruit",
    emoji: "🍊",
    level: "college",
    logo: NCAA(183),
    image: IMG("otto-orange"),
  },
  {
    name: "Demon Deacon",
    team: "Demon Deacons",
    city: "Wake Forest",
    league: "ACC",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(154),
    image: IMG("demon-deacon"),
  },
  {
    name: "Blue Devil",
    team: "Blue Devils",
    city: "Duke",
    league: "ACC",
    animal: "devil",
    emoji: "😈",
    level: "college",
    logo: NCAA(150),
    image: IMG("blue-devil"),
  },
  {
    name: "Rameses",
    team: "Tar Heels",
    city: "North Carolina",
    league: "ACC",
    animal: "ram",
    emoji: "🐏",
    level: "college",
    logo: NCAA(153),
    image: IMG("rameses"),
  },
  {
    name: "Mr. Wuf",
    team: "Wolfpack",
    city: "NC State",
    league: "ACC",
    animal: "wolf",
    emoji: "🐺",
    level: "college",
    logo: NCAA(152),
    image: IMG("mr-wuf"),
  },
  {
    name: "Stanford Tree",
    team: "Cardinal",
    city: "Stanford",
    league: "ACC",
    animal: "tree",
    emoji: "🌲",
    level: "college",
    logo: NCAA(24),
    image: IMG("stanford-tree"),
  },

  {
    name: "Big Al",
    team: "Crimson Tide",
    city: "Alabama",
    league: "SEC",
    animal: "elephant",
    emoji: "🐘",
    level: "college",
    logo: NCAA(333),
    image: IMG("big-al"),
  },
  {
    name: "Aubie",
    team: "Tigers",
    city: "Auburn",
    league: "SEC",
    animal: "tiger",
    emoji: "🐯",
    level: "college",
    logo: NCAA(2),
    image: IMG("aubie"),
  },
  {
    name: "Smokey",
    team: "Volunteers",
    city: "Tennessee",
    league: "SEC",
    animal: "dog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(2633),
    image: IMG("smokey"),
  },
  {
    name: "Albert Gator",
    team: "Gators",
    city: "Florida",
    league: "SEC",
    animal: "gator",
    emoji: "🐊",
    level: "college",
    logo: NCAA(57),
    image: IMG("albert-gator"),
  },
  {
    name: "Mike the Tiger",
    team: "Tigers",
    city: "LSU",
    league: "SEC",
    animal: "tiger",
    emoji: "🐯",
    level: "college",
    logo: NCAA(99),
    image: IMG("mike-tiger"),
  },
  {
    name: "Reveille",
    team: "Aggies",
    city: "Texas A&M",
    league: "SEC",
    animal: "dog",
    emoji: "🐕",
    level: "college",
    logo: NCAA(245),
    image: IMG("reveille"),
  },
  {
    name: "Cocky",
    team: "Gamecocks",
    city: "South Carolina",
    league: "SEC",
    animal: "rooster",
    emoji: "🐓",
    level: "college",
    logo: NCAA(2579),
    image: IMG("cocky"),
  },
  {
    name: "Bevo",
    team: "Longhorns",
    city: "Texas",
    league: "SEC",
    animal: "longhorn",
    emoji: "🐂",
    level: "college",
    logo: NCAA(251),
    image: IMG("bevo"),
  },
  {
    name: "Boomer",
    team: "Sooners",
    city: "Oklahoma",
    league: "SEC",
    animal: "horse",
    emoji: "🐎",
    level: "college",
    logo: NCAA(201),
    image: IMG("sooner-ou"),
  },
  {
    name: "Hairy Dawg",
    team: "Bulldogs",
    city: "Georgia",
    league: "SEC",
    animal: "dog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(61),
    image: IMG("uga"),
  },
  {
    name: "Truman the Tiger",
    team: "Tigers",
    city: "Missouri",
    league: "SEC",
    animal: "tiger",
    emoji: "🐯",
    level: "college",
    logo: NCAA(142),
    image: IMG("truman-tiger"),
  },

  // Big 12
  {
    name: "Big Jay",
    team: "Jayhawks",
    city: "Kansas",
    league: "Big 12",
    animal: "jayhawk",
    emoji: "🦅",
    level: "college",
    logo: NCAA(2305),
    image: IMG("big-jay"),
  },
  {
    name: "Ralphie",
    team: "Buffaloes",
    city: "Colorado",
    league: "Big 12",
    animal: "buffalo",
    emoji: "🐃",
    level: "college",
    logo: NCAA(38),
    image: IMG("ralphie"),
  },
  {
    name: "Cy the Cardinal",
    team: "Cyclones",
    city: "Iowa State",
    league: "Big 12",
    animal: "bird",
    emoji: "🐦",
    level: "college",
    logo: NCAA(66),
    image: IMG("cy-cyclone"),
  },
  {
    name: "Pistol Pete",
    team: "Cowboys",
    city: "Oklahoma State",
    league: "Big 12",
    animal: "human",
    emoji: "🤠",
    level: "college",
    logo: NCAA(197),
    image: IMG("pistol-pete"),
  },
  {
    name: "Willie the Wildcat",
    team: "Wildcats",
    city: "Kansas State",
    league: "Big 12",
    animal: "wildcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(2306),
    image: IMG("willie-the-wildcat-ksu"),
  },
  {
    name: "Cosmo",
    team: "Cougars",
    city: "BYU",
    league: "Big 12",
    animal: "cougar",
    emoji: "🦁",
    level: "college",
    logo: NCAA(252),
    image: IMG("cosmo"),
  },
  {
    name: "Wilbur & Wilma",
    team: "Wildcats",
    city: "Arizona",
    league: "Big 12",
    animal: "wildcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(12),
    image: IMG("wilbur-wilma"),
  },
  {
    name: "Sparky the Sun Devil",
    team: "Sun Devils",
    city: "Arizona State",
    league: "Big 12",
    animal: "devil",
    emoji: "😈",
    level: "college",
    logo: NCAA(9),
    image: IMG("sparky-sun-devil"),
  },
  {
    name: "Sic 'em Bear",
    team: "Bears",
    city: "Baylor",
    league: "Big 12",
    animal: "bear",
    emoji: "🐻",
    level: "college",
    logo: NCAA(239),
    image: IMG("sic-em-bear"),
  },
  {
    name: "Bearcat",
    team: "Bearcats",
    city: "Cincinnati",
    league: "Big 12",
    animal: "bearcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(2132),
    image: IMG("bearcat"),
  },
  {
    name: "SuperFrog",
    team: "Horned Frogs",
    city: "TCU",
    league: "Big 12",
    animal: "frog",
    emoji: "🐸",
    level: "college",
    logo: NCAA(2628),
    image: IMG("superfrog"),
  },
  {
    name: "Hook 'Em",
    team: "Longhorns",
    city: "Texas",
    league: "Big 12",
    animal: "longhorn",
    emoji: "🐂",
    level: "college",
    logo: NCAA(251),
    image: IMG("hook-em"),
  },
  {
    name: "Raider Red",
    team: "Red Raiders",
    city: "Texas Tech",
    league: "Big 12",
    animal: "human",
    emoji: "🤠",
    level: "college",
    logo: NCAA(2641),
    image: IMG("raider-red"),
  },
  {
    name: "Knightro",
    team: "Knights",
    city: "UCF",
    league: "Big 12",
    animal: "knight",
    emoji: "⚔️",
    level: "college",
    logo: NCAA(2116),
    image: IMG("knightro"),
  },
  {
    name: "Swoop",
    team: "Utes",
    city: "Utah",
    league: "Big 12",
    animal: "bird",
    emoji: "🦅",
    level: "college",
    logo: NCAA(254),
    image: IMG("swoop-utah"),
  },
  {
    name: "Mountaineer",
    team: "Mountaineers",
    city: "West Virginia",
    league: "Big 12",
    animal: "human",
    emoji: "🪖",
    level: "college",
    logo: NCAA(277),
    image: IMG("mountaineer"),
  },
  {
    name: "Shasta",
    team: "Cougars",
    city: "Houston",
    league: "Big 12",
    animal: "cougar",
    emoji: "🦁",
    level: "college",
    logo: NCAA(248),
    image: IMG("shasta"),
  },

  {
    name: "The Leprechaun",
    team: "Fighting Irish",
    city: "Notre Dame",
    league: "Independent",
    animal: "leprechaun",
    emoji: "☘️",
    level: "college",
    logo: NCAA(87),
    image: IMG("leprechaun"),
  },
  {
    name: "Jonathan the Husky",
    team: "Huskies",
    city: "UConn",
    league: "Big East",
    animal: "dog",
    emoji: "🐕",
    level: "college",
    logo: NCAA(41),
    image: IMG("jonathan-the-husky"),
  },
  // Big East
  {
    name: "Blue III",
    team: "Bulldogs",
    city: "Butler",
    league: "Big East",
    animal: "bulldog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(2086),
    image: IMG("blue-iii"),
  },
  {
    name: "Billy Bluejay",
    team: "Bluejays",
    city: "Creighton",
    league: "Big East",
    animal: "bird",
    emoji: "🐦",
    level: "college",
    logo: NCAA(156),
    image: IMG("billy-bluejay"),
  },
  {
    name: "Dibs",
    team: "Blue Demons",
    city: "DePaul",
    league: "Big East",
    animal: "devil",
    emoji: "😈",
    level: "college",
    logo: NCAA(305),
    image: IMG("dibs-blue-demon"),
  },
  {
    name: "Jack the Bulldog",
    team: "Hoyas",
    city: "Georgetown",
    league: "Big East",
    animal: "bulldog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(46),
    image: IMG("jack-the-bulldog"),
  },
  {
    name: "Golden Eagle",
    team: "Golden Eagles",
    city: "Marquette",
    league: "Big East",
    animal: "eagle",
    emoji: "🦅",
    level: "college",
    logo: NCAA(269),
    image: IMG("golden-eagle"),
  },
  {
    name: "Friar Dom",
    team: "Friars",
    city: "Providence",
    league: "Big East",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(2507),
    image: IMG("friar-dom"),
  },
  {
    name: "Johnny Thunderbird",
    team: "Red Storm",
    city: "St. John's",
    league: "Big East",
    animal: "bird",
    emoji: "🐦",
    level: "college",
    logo: NCAA(2599),
    image: IMG("johnny-thunder"),
  },
  {
    name: "Pirate Pete",
    team: "Pirates",
    city: "Seton Hall",
    league: "Big East",
    animal: "human",
    emoji: "🏴‍☠️",
    level: "college",
    logo: NCAA(2550),
    image: IMG("pirate-pete-shu"),
  },
  {
    name: "Will D. Cat",
    team: "Wildcats",
    city: "Villanova",
    league: "Big East",
    animal: "wildcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(222),
    image: IMG("will-d-cat"),
  },
  {
    name: "Xavier Musketeer",
    team: "Musketeers",
    city: "Xavier",
    league: "Big East",
    animal: "human",
    emoji: "🗡️",
    level: "college",
    logo: NCAA(2752),
    image: IMG("xavier-musketeer"),
  },
  {
    name: "Sam the Minuteman",
    team: "Minutemen",
    city: "UMass",
    league: "Big East",
    animal: "human",
    emoji: "🪖",
    level: "college",
    logo: NCAA(113),
    image: IMG("sam-minuteman"),
  },
  {
    name: "River Hawk",
    team: "River Hawks",
    city: "UMass Lowell",
    league: "Big East",
    animal: "hawk",
    emoji: "🦅",
    level: "college",
    logo: NCAA(2349),
    image: IMG("river-hawk"),
  },
  {
    name: "Bonnie",
    team: "Bonnies",
    city: "St. Bonaventure",
    league: "Big East",
    animal: "creature",
    emoji: "🟤",
    level: "college",
    logo: NCAA(179),
    image: IMG("bonnie-bonnies"),
  },

  // Smaller D1 (basketball-strong, no FBS football) — no photos yet,
  // adds logo-recognition + conference-trivia difficulty.
  {
    name: "Spike",
    team: "Bulldogs",
    city: "Gonzaga",
    league: "WCC",
    animal: "bulldog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(2250),
    image: IMG("spike-gonzaga"),
  },
  {
    name: "The Gael",
    team: "Gaels",
    city: "Saint Mary's",
    league: "WCC",
    animal: "human",
    emoji: "⚔️",
    level: "college",
    logo: NCAA(2608),
    image: IMG("gael"),
  },
  {
    name: "Lux Cat",
    team: "Wildcats",
    city: "Davidson",
    league: "A-10",
    animal: "wildcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(2166),
    image: IMG("lux-cat"),
  },
  {
    name: "Rudy Flyer",
    team: "Flyers",
    city: "Dayton",
    league: "A-10",
    animal: "human",
    emoji: "✈️",
    level: "college",
    logo: NCAA(2168),
    image: IMG("rudy-flyer"),
  },
  {
    name: "The Hawk",
    team: "Hawks",
    city: "Saint Joseph's",
    league: "A-10",
    animal: "hawk",
    emoji: "🦅",
    level: "college",
    logo: NCAA(2603),
    image: IMG("sju-hawk"),
  },
  {
    name: "Rodney the Ram",
    team: "Rams",
    city: "VCU",
    league: "A-10",
    animal: "ram",
    emoji: "🐏",
    level: "college",
    logo: NCAA(2670),
    image: IMG("rodney-ram"),
  },
  {
    name: "Patriot",
    team: "Patriots",
    city: "George Mason",
    league: "A-10",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(2244),
    image: IMG("mason-patriot"),
  },
  {
    name: "LU Wolf",
    team: "Ramblers",
    city: "Loyola Chicago",
    league: "A-10",
    animal: "wolf",
    emoji: "🐺",
    level: "college",
    logo: NCAA(2350),
    image: IMG("lu-wolf"),
  },
  {
    name: "WuShock",
    team: "Shockers",
    city: "Wichita State",
    league: "AAC",
    animal: "wheat",
    emoji: "🌾",
    level: "college",
    logo: NCAA(2724),
    image: IMG("wushock"),
  },
  {
    name: "Handsome Dan",
    team: "Bulldogs",
    city: "Yale",
    league: "Ivy League",
    animal: "bulldog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(43),
    image: IMG("handsome-dan"),
  },
  {
    name: "The Tiger",
    team: "Tigers",
    city: "Princeton",
    league: "Ivy League",
    animal: "tiger",
    emoji: "🐯",
    level: "college",
    logo: NCAA(163),
    image: IMG("princeton-tiger"),
  },
  // Rest of Ivy League
  {
    name: "Boomer the Bear",
    team: "Bears",
    city: "Brown",
    league: "Ivy League",
    animal: "bear",
    emoji: "🐻",
    level: "college",
    logo: NCAA(225),
    image: IMG("boomer-bear"),
  },
  {
    name: "Roaree the Lion",
    team: "Lions",
    city: "Columbia",
    league: "Ivy League",
    animal: "lion",
    emoji: "🦁",
    level: "college",
    logo: NCAA(171),
    image: IMG("roaree"),
  },
  {
    name: "Touchdown the Bear",
    team: "Big Red",
    city: "Cornell",
    league: "Ivy League",
    animal: "bear",
    emoji: "🐻",
    level: "college",
    logo: NCAA(172),
    image: IMG("touchdown-bear"),
  },
  {
    name: "The Big Green",
    team: "Big Green",
    city: "Dartmouth",
    league: "Ivy League",
    animal: "human",
    emoji: "🟢",
    level: "college",
    logo: NCAA(159),
    image: IMG("big-green"),
  },
  {
    name: "John Harvard",
    team: "Crimson",
    city: "Harvard",
    league: "Ivy League",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(108),
    image: IMG("john-harvard"),
  },
  {
    name: "The Penn Quaker",
    team: "Quakers",
    city: "Penn",
    league: "Ivy League",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(219),
    image: IMG("penn-quaker"),
  },
  {
    name: "Bananas T. Bear",
    team: "Black Bears",
    city: "Maine",
    league: "America East",
    animal: "bear",
    emoji: "🐻",
    level: "college",
    logo: NCAA(311),
    image: IMG("bananas-bear"),
  },
  {
    name: "Rally",
    team: "Catamounts",
    city: "Vermont",
    league: "America East",
    animal: "cat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(261),
  },
  {
    name: "Damien",
    team: "Great Danes",
    city: "Albany",
    league: "America East",
    animal: "dog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(399),
    image: IMG("damien-great-dane"),
  },
  {
    name: "Howie the Hawk",
    team: "Hawks",
    city: "Hartford",
    league: "America East",
    animal: "hawk",
    emoji: "🦅",
    level: "college",
    logo: NCAA(42),
    image: IMG("howie-hawk-hartford"),
  },

  // PAC-12 (current — Oregon State + Washington State remain)
  {
    name: "Benny the Beaver",
    team: "Beavers",
    city: "Oregon State",
    league: "PAC-12",
    animal: "beaver",
    emoji: "🦫",
    level: "college",
    logo: NCAA(204),
    image: IMG("benny-beaver"),
  },
  {
    name: "Butch T. Cougar",
    team: "Cougars",
    city: "Washington State",
    league: "PAC-12",
    animal: "cougar",
    emoji: "🦁",
    level: "college",
    logo: NCAA(265),
    image: IMG("butch-cougar"),
  },
  {
    name: "Traveler",
    team: "Trojans",
    city: "USC",
    league: "Big Ten",
    animal: "horse",
    emoji: "🐎",
    level: "college",
    logo: NCAA(30),
    image: IMG("traveler"),
  },

  // American Athletic Conference (AAC)
  {
    name: "Niner Norm",
    team: "49ers",
    city: "Charlotte",
    league: "AAC",
    animal: "miner",
    emoji: "⛏️",
    level: "college",
    logo: NCAA(2429),
    image: IMG("niner-norm"),
  },
  {
    name: "PeeDee the Pirate",
    team: "Pirates",
    city: "East Carolina",
    league: "AAC",
    animal: "human",
    emoji: "🏴‍☠️",
    level: "college",
    logo: NCAA(151),
    image: IMG("ecu-pirate"),
  },
  {
    name: "Owlsley",
    team: "Owls",
    city: "Florida Atlantic",
    league: "AAC",
    animal: "owl",
    emoji: "🦉",
    level: "college",
    logo: NCAA(2226),
    image: IMG("owlsley"),
  },
  {
    name: "Tom the Tiger",
    team: "Tigers",
    city: "Memphis",
    league: "AAC",
    animal: "tiger",
    emoji: "🐯",
    level: "college",
    logo: NCAA(235),
    image: IMG("tom-tiger"),
  },
  {
    name: "Scrappy",
    team: "Mean Green",
    city: "North Texas",
    league: "AAC",
    animal: "eagle",
    emoji: "🦅",
    level: "college",
    logo: NCAA(249),
    image: IMG("scrappy-unt"),
  },
  {
    name: "Sammy the Owl",
    team: "Owls",
    city: "Rice",
    league: "AAC",
    animal: "owl",
    emoji: "🦉",
    level: "college",
    logo: NCAA(242),
    image: IMG("sammy-owl"),
  },
  {
    name: "Rocky the Bull",
    team: "Bulls",
    city: "South Florida",
    league: "AAC",
    animal: "bull",
    emoji: "🐂",
    level: "college",
    logo: NCAA(58),
    image: IMG("rocky-bull"),
  },
  {
    name: "Riptide the Wave",
    team: "Green Wave",
    city: "Tulane",
    league: "AAC",
    animal: "pelican",
    emoji: "🦩",
    level: "college",
    logo: NCAA(2655),
    image: IMG("riptide"),
  },
  {
    name: "Captain Cane",
    team: "Golden Hurricane",
    city: "Tulsa",
    league: "AAC",
    animal: "human",
    emoji: "🌪️",
    level: "college",
    logo: NCAA(202),
    image: IMG("captain-cane"),
  },

  // Mid-American Conference (MAC)
  {
    name: "Zippy",
    team: "Zips",
    city: "Akron",
    league: "MAC",
    animal: "kangaroo",
    emoji: "🦘",
    level: "college",
    logo: NCAA(2006),
    image: IMG("zippy"),
  },
  {
    name: "Freddy Falcon",
    team: "Falcons",
    city: "Bowling Green",
    league: "MAC",
    animal: "falcon",
    emoji: "🦅",
    level: "college",
    logo: NCAA(189),
    image: IMG("freddy-falcon-bg"),
  },
  {
    name: "Rufus the Bobcat",
    team: "Bobcats",
    city: "Ohio",
    league: "MAC",
    animal: "bobcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(195),
    image: IMG("rufus-bobcat"),
  },

  // Sun Belt
  {
    name: "Yodel the Mountaineer",
    team: "Mountaineers",
    city: "Appalachian State",
    league: "Sun Belt",
    animal: "human",
    emoji: "🪕",
    level: "college",
    logo: NCAA(2026),
    image: IMG("yodel"),
  },
  {
    name: "The Chanticleer",
    team: "Chanticleers",
    city: "Coastal Carolina",
    league: "Sun Belt",
    animal: "rooster",
    emoji: "🐓",
    level: "college",
    logo: NCAA(324),
    image: IMG("chanticleer"),
  },
  {
    name: "Duke Dog",
    team: "Dukes",
    city: "James Madison",
    league: "Sun Belt",
    animal: "dog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(256),
    image: IMG("duke-dog"),
  },

  // Conference USA (selected)
  {
    name: "LU the Eagle",
    team: "Flames",
    city: "Liberty",
    league: "CUSA",
    animal: "eagle",
    emoji: "🦅",
    level: "college",
    logo: NCAA(2335),
    image: IMG("lu-eagle"),
  },
  {
    name: "Sammy Bearkat",
    team: "Bearkats",
    city: "Sam Houston",
    league: "CUSA",
    animal: "bearkat",
    emoji: "🐻",
    level: "college",
    logo: NCAA(2534),
    image: IMG("sammy-bearkat"),
  },
  {
    name: "Big Red",
    team: "Hilltoppers",
    city: "Western Kentucky",
    league: "CUSA",
    animal: "creature",
    emoji: "🟥",
    level: "college",
    logo: NCAA(98),
    image: IMG("big-red-wku"),
  },

  // Atlantic 10 (additional)
  {
    name: "Rose Hill Ram",
    team: "Rams",
    city: "Fordham",
    league: "A-10",
    animal: "ram",
    emoji: "🐏",
    level: "college",
    logo: NCAA(2230),
    image: IMG("rose-hill-ram"),
  },
  {
    name: "George the Colonial",
    team: "Colonials",
    city: "George Washington",
    league: "A-10",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(45),
    image: IMG("gw-colonial"),
  },
  {
    name: "Rhody",
    team: "Rams",
    city: "Rhode Island",
    league: "A-10",
    animal: "ram",
    emoji: "🐏",
    level: "college",
    logo: NCAA(227),
    image: IMG("rhody"),
  },
  {
    name: "Webstur",
    team: "Spiders",
    city: "Richmond",
    league: "A-10",
    animal: "spider",
    emoji: "🕷️",
    level: "college",
    logo: NCAA(257),
    image: IMG("webstur"),
  },

  // West Coast Conference
  {
    name: "The Lion",
    team: "Lions",
    city: "Loyola Marymount",
    league: "WCC",
    animal: "lion",
    emoji: "🦁",
    level: "college",
    logo: NCAA(2351),
    image: IMG("lmu-lion"),
  },
  {
    name: "Willie the Wave",
    team: "Waves",
    city: "Pepperdine",
    league: "WCC",
    animal: "human",
    emoji: "🌊",
    level: "college",
    logo: NCAA(2492),
    image: IMG("willie-the-wave"),
  },
  {
    name: "Tom the Tiger",
    team: "Tigers",
    city: "Pacific",
    league: "WCC",
    animal: "tiger",
    emoji: "🐯",
    level: "college",
    logo: NCAA(279),
    image: IMG("tom-tiger-pacific"),
  },
  {
    name: "Don",
    team: "Dons",
    city: "San Francisco",
    league: "WCC",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(2539),
    image: IMG("san-fran-don"),
  },

  // Missouri Valley
  {
    name: "Bruin the Bear",
    team: "Bruins",
    city: "Belmont",
    league: "MVC",
    animal: "bear",
    emoji: "🐻",
    level: "college",
    logo: NCAA(2057),
    image: IMG("bruin-belmont"),
  },
  {
    name: "Spike (Drake)",
    team: "Bulldogs",
    city: "Drake",
    league: "MVC",
    animal: "bulldog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(2181),
    image: IMG("spike-drake"),
  },
  {
    name: "Reggie Redbird",
    team: "Redbirds",
    city: "Illinois State",
    league: "MVC",
    animal: "bird",
    emoji: "🐦",
    level: "college",
    logo: NCAA(2287),
    image: IMG("reggie-isu"),
  },
  {
    name: "Sycamore Sam",
    team: "Sycamores",
    city: "Indiana State",
    league: "MVC",
    animal: "tree",
    emoji: "🌲",
    level: "college",
    logo: NCAA(282),
    image: IMG("sycamore-sam"),
  },
  {
    name: "TC the Panther",
    team: "Panthers",
    city: "Northern Iowa",
    league: "MVC",
    animal: "panther",
    emoji: "🐱",
    level: "college",
    logo: NCAA(2460),
    image: IMG("tc-uni"),
  },

  // MAAC (Metro Atlantic)
  {
    name: "Petey the Peacock",
    team: "Peacocks",
    city: "Saint Peter's",
    league: "MAAC",
    animal: "peacock",
    emoji: "🦚",
    level: "college",
    logo: NCAA(2612),
    image: IMG("petey-peacock"),
  },
  {
    name: "Boomer (Quinnipiac)",
    team: "Bobcats",
    city: "Quinnipiac",
    league: "MAAC",
    animal: "bobcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(2514),
    image: IMG("bobcat-quinnipiac"),
  },

  // CAA
  {
    name: "YoUDee",
    team: "Blue Hens",
    city: "Delaware",
    league: "CAA",
    animal: "chicken",
    emoji: "🐔",
    level: "college",
    logo: NCAA(48),
    image: IMG("youdee"),
  },
  {
    name: "Drex the Dragon",
    team: "Dragons",
    city: "Drexel",
    league: "CAA",
    animal: "dragon",
    emoji: "🐉",
    level: "college",
    logo: NCAA(2182),
    image: IMG("drex"),
  },
  {
    name: "Sammy the Seahawk",
    team: "Seahawks",
    city: "UNC Wilmington",
    league: "CAA",
    animal: "seahawk",
    emoji: "🦅",
    level: "college",
    logo: NCAA(350),
    image: IMG("sammy-seahawk"),
  },

  // Big Sky
  {
    name: "Joe Vandal",
    team: "Vandals",
    city: "Idaho",
    league: "Big Sky",
    animal: "human",
    emoji: "🪓",
    level: "college",
    logo: NCAA(70),
    image: IMG("vandal"),
  },
  {
    name: "Louie the Lumberjack",
    team: "Lumberjacks",
    city: "Northern Arizona",
    league: "Big Sky",
    animal: "human",
    emoji: "🪓",
    level: "college",
    logo: NCAA(2464),
    image: IMG("louie-lumberjack"),
  },

  // Patriot League
  {
    name: "Bill the Goat",
    team: "Midshipmen",
    city: "Navy",
    league: "Patriot League",
    animal: "goat",
    emoji: "🐐",
    level: "college",
    logo: NCAA(2426),
    image: IMG("bill-goat-navy"),
  },
  {
    name: "Bucky the Bison",
    team: "Bison",
    city: "Bucknell",
    league: "Patriot League",
    animal: "bison",
    emoji: "🐃",
    level: "college",
    logo: NCAA(2083),
    image: IMG("bison-bucknell"),
  },
  {
    name: "Rhett the Terrier",
    team: "Terriers",
    city: "Boston University",
    league: "Patriot League",
    animal: "terrier",
    emoji: "🐶",
    level: "college",
    logo: NCAA(104),
    image: IMG("rhett-bu"),
  },
  {
    name: "Holy Cross Crusader",
    team: "Crusaders",
    city: "Holy Cross",
    league: "Patriot League",
    animal: "human",
    emoji: "✝️",
    level: "college",
    logo: NCAA(107),
    image: IMG("holy-cross-eagle"),
  },

  // SoCon
  {
    name: "The Citadel General",
    team: "Bulldogs",
    city: "The Citadel",
    league: "SoCon",
    animal: "human",
    emoji: "🪖",
    level: "college",
    logo: NCAA(2127),
    image: IMG("general-citadel"),
  },

  // Southland Conference
  {
    name: "Boomtown",
    team: "Cardinals",
    city: "Lamar",
    league: "Southland",
    animal: "lion",
    emoji: "🦁",
    level: "college",
    logo: NCAA(2320),
    image: IMG("boomtown-lamar"),
  },
  {
    name: "Sammy the Cowboy",
    team: "Cowboys",
    city: "McNeese",
    league: "Southland",
    animal: "human",
    emoji: "🤠",
    level: "college",
    logo: NCAA(2377),
    image: IMG("sammy-cowboy"),
  },
  {
    name: "Colonel Tillou",
    team: "Colonels",
    city: "Nicholls",
    league: "Southland",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(2447),
    image: IMG("colonel-nicholls"),
  },
  {
    name: "Vic the Demon",
    team: "Demons",
    city: "Northwestern State",
    league: "Southland",
    animal: "devil",
    emoji: "😈",
    level: "college",
    logo: NCAA(2466),
    image: IMG("demon-nwst"),
  },
  {
    name: "Izzy the Islander",
    team: "Islanders",
    city: "Texas A&M–Corpus Christi",
    league: "Southland",
    animal: "human",
    emoji: "🏝️",
    level: "college",
    logo: NCAA(357),
    image: IMG("islander-tamucc"),
  },
  {
    name: "Dusty the Cardinal",
    team: "Cardinals",
    city: "Incarnate Word",
    league: "Southland",
    animal: "bird",
    emoji: "🐦",
    level: "college",
    logo: NCAA(2916),
    image: IMG("dusty-cardinal"),
  },

  // Ohio Valley Conference (OVC)
  {
    name: "Awoo the Golden Eagle",
    team: "Golden Eagles",
    city: "Tennessee Tech",
    league: "OVC",
    animal: "eagle",
    emoji: "🦅",
    level: "college",
    logo: NCAA(2635),
    image: IMG("awoo-eagle"),
  },
  {
    name: "The Governor",
    team: "Governors",
    city: "Austin Peay",
    league: "OVC",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(2046),
    image: IMG("governor-peay"),
  },
  {
    name: "Racer One",
    team: "Racers",
    city: "Murray State",
    league: "OVC",
    animal: "horse",
    emoji: "🐎",
    level: "college",
    logo: NCAA(93),
    image: IMG("racer-one"),
  },
  {
    name: "Captain Skyhawk",
    team: "Skyhawks",
    city: "UT Martin",
    league: "OVC",
    animal: "hawk",
    emoji: "🦅",
    level: "college",
    logo: NCAA(2630),
    image: IMG("skyhawk-utm"),
  },
  {
    name: "Eddie the Cougar",
    team: "Cougars",
    city: "SIUE",
    league: "OVC",
    animal: "cougar",
    emoji: "🦁",
    level: "college",
    logo: NCAA(2565),
    image: IMG("eddie-cougar"),
  },

  // SEC additions (from SEC grid)
  {
    name: "Tusk",
    team: "Razorbacks",
    city: "Arkansas",
    league: "SEC",
    animal: "razorback",
    emoji: "🐗",
    level: "college",
    logo: NCAA(8),
    image: IMG("tusk"),
  },
  {
    name: "The Wildcat",
    team: "Wildcats",
    city: "Kentucky",
    league: "SEC",
    animal: "wildcat",
    emoji: "🐱",
    level: "college",
    logo: NCAA(96),
    image: IMG("kentucky-wildcat"),
  },
  {
    name: "Rebel Black Bear",
    team: "Rebels",
    city: "Ole Miss",
    league: "SEC",
    animal: "bear",
    emoji: "🐻",
    level: "college",
    logo: NCAA(145),
    image: IMG("rebel-black-bear"),
  },
  {
    name: "Bully",
    team: "Bulldogs",
    city: "Mississippi State",
    league: "SEC",
    animal: "bulldog",
    emoji: "🐶",
    level: "college",
    logo: NCAA(344),
    image: IMG("bully"),
  },
  {
    name: "Mr. C",
    team: "Commodores",
    city: "Vanderbilt",
    league: "SEC",
    animal: "human",
    emoji: "🎩",
    level: "college",
    logo: NCAA(238),
    image: IMG("mr-c"),
  },

  // ACC additions (from ACC grid)
  {
    name: "Baldwin the Eagle",
    team: "Eagles",
    city: "Boston College",
    league: "ACC",
    animal: "eagle",
    emoji: "🦅",
    level: "college",
    logo: NCAA(103),
    image: IMG("baldwin-eagle"),
  },
  {
    name: "The Tiger (Clemson)",
    team: "Tigers",
    city: "Clemson",
    league: "ACC",
    animal: "tiger",
    emoji: "🐯",
    level: "college",
    logo: NCAA(228),
    image: IMG("clemson-tiger"),
  },
  {
    name: "Chief Osceola",
    team: "Seminoles",
    city: "Florida State",
    league: "ACC",
    animal: "human",
    emoji: "🪶",
    level: "college",
    logo: NCAA(52),
    image: IMG("chief-osceola"),
  },
  {
    name: "Buzz",
    team: "Yellow Jackets",
    city: "Georgia Tech",
    league: "ACC",
    animal: "yellow-jacket",
    emoji: "🐝",
    level: "college",
    logo: NCAA(59),
    image: IMG("buzz"),
  },
  {
    name: "The Cardinal Bird",
    team: "Cardinals",
    city: "Louisville",
    league: "ACC",
    animal: "bird",
    emoji: "🐦",
    level: "college",
    logo: NCAA(97),
    image: IMG("louisville-cardinal"),
  },
  {
    name: "Roc the Panther",
    team: "Panthers",
    city: "Pitt",
    league: "ACC",
    animal: "panther",
    emoji: "🐱",
    level: "college",
    logo: NCAA(221),
    image: IMG("roc-panther"),
  },
  {
    name: "Peruna",
    team: "Mustangs",
    city: "SMU",
    league: "ACC",
    animal: "horse",
    emoji: "🐴",
    level: "college",
    logo: NCAA(2567),
    image: IMG("peruna"),
  },
  {
    name: "CavMan",
    team: "Cavaliers",
    city: "Virginia",
    league: "ACC",
    animal: "human",
    emoji: "🤺",
    level: "college",
    logo: NCAA(258),
    image: IMG("cavman"),
  },
];
